<?php
declare(strict_types=1);

return [
    'meta' => [
        'title' => 'Chú Bé Rồng Online - Ngọc Rồng Online',
        'keywords' => 'Chú Bé Rồng Online, Ngọc Rồng Online, Ngoc Rong Online, Ngọc Rồng Mobile, Dragon Ball Online, game ngọc rồng',
        'description' => 'Website chính thức của Chú Bé Rồng Online - game nhập vai trực tuyến trên máy tính và điện thoại.',
        'refresh' => '600',
        'robots' => 'INDEX,FOLLOW',
        'og_title' => 'Chú Bé Rồng Online - Ngọc Rồng Online',
        'og_description' => 'Game 7 viên ngọc rồng hàng đầu trên mobile và PC.',
    ],
    'links' => [
        'forum' => '',
        'fanpage' => '',
        'terms' => 'http://teamobi.com/dieukhoan.htm',
        'discord' => '',
        'zalo_boxes' => [],
        'footer_games' => [],
    ],
    'pages' => [
        '/' => [
            'id' => 'trang-chu',
            'title' => 'Trang Chủ - Chú Bé Rồng Online - Ngọc Rồng Online',
            'view' => 'trang-chu',
            'show_forum_banner' => true,
            'extra_css' => [],
            'extra_js' => [],
            'canonical' => '/',
        ],
        '/trang-chu' => [
            'id' => 'trang-chu',
            'title' => 'Trang Chủ - Chú Bé Rồng Online - Ngọc Rồng Online',
            'view' => 'trang-chu',
            'show_forum_banner' => true,
            'extra_css' => [],
            'extra_js' => [],
            'canonical' => '/trang-chu',
        ],
        '/gioi-thieu' => [
            'id' => 'gioi-thieu',
            'title' => 'Giới Thiệu - Chú Bé Rồng Online - Ngọc Rồng Online',
            'view' => 'gioi-thieu',
            'show_forum_banner' => false,
            'extra_css' => ['css/css-info.css'],
            'extra_js' => ['js/js-info.js'],
            'canonical' => '/gioi-thieu',
        ],
        '/dang-ky' => [
            'id' => 'dang-ky',
            'title' => 'Đăng Ký - Ngọc Rồng Online',
            'view' => 'dang-ky',
            'show_forum_banner' => false,
            'extra_css' => [],
            'extra_js' => [],
            'canonical' => '/dang-ky',
        ],
        '/dang-nhap' => [
            'id' => 'dang-nhap',
            'title' => 'Đăng Nhập - Ngọc Rồng Online',
            'view' => 'dang-nhap',
            'show_forum_banner' => false,
            'extra_css' => [],
            'extra_js' => [],
            'canonical' => '/dang-nhap',
        ],
        '/nap-tien' => [
            'id' => 'nap-tien',
            'title' => 'Nạp Tiền - Ngọc Rồng Online',
            'view' => 'nap-tien',
            'show_forum_banner' => false,
            'extra_css' => [],
            'extra_js' => [],
            'canonical' => '/nap-tien',
        ],
        '/dien-dan' => [
            'id' => 'dien-dan',
            'title' => 'Diễn Đàn Góp Ý - Ngọc Rồng Online',
            'view' => 'dien-dan',
            'show_forum_banner' => false,
            'extra_css' => [],
            'extra_js' => [],
            'canonical' => '/dien-dan',
        ],
    ],
    'not_found' => [
        'id' => '404',
        'title' => '404 - Ngọc Rồng Online',
        'view' => '404',
        'show_forum_banner' => false,
        'extra_css' => [],
        'extra_js' => [],
        'canonical' => '/',
    ],
];
